name: Build Custom Theme

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'master'
    types: [opened, synchronize, reopened]
  
jobs:
  build:
    name: Build Custom Theme
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Keycloak Repository
      uses: actions/checkout@v2

    - name: Install node version 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install pnpm version 8.15.9
      run: npm install -g pnpm@8.15.9

    - name: Install java version 17 of openjdk
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Install maven version 3.8.4
      run: |
        sudo apt-get install maven
        mvn -version

    - name: Get keycloak version
      run: ./get-version.sh

    - name: Set version of keycloak using set-version.sh
      run: |
        ./set-version.sh 26.0.6

    - name: Build Keycloak using mvn
      run: ./mvnw clean install -DskipTests

    - name: Print whole structure of keycloak
      run: ls -R

    - name: Copy account ui theme to s3 bucket
      run: |
        aws s3 cp js/apps/account-ui/target/keycloak-account-ui-26.0.6.jar s3://testbucketforcloudflare/keycloak-26-account-ui-theme/
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}